[project]
name = "automate-dv-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "dbt-core>=1.10.1",
    "dbt-snowflake>=1.9.4",
]
